sudo: required
services:
    - docker

before_install:
    - docker build -t mozyk27/docker-react1 -f Dockerfile.dev .

script:
    - docker run mozyk27/docker-react1 npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react1"
    env: "DockerReact1-env"
    bucket_name: "elasticbeanstalk-us-east-1-460135069946"
    bucket_path: "docker-react1"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
